- id: '1729963391488'
  alias: Front Garden Cory Returns
  description: ''
  triggers:
  - trigger: zone
    entity_id: person.cory
    zone: zone.home_extended
    event: enter
  - trigger: zone
    entity_id: person.debs
    zone: zone.home_extended
    event: enter
  conditions:
  - condition: sun
    after: sunset
  actions:
  - action: light.turn_on
    target:
      device_id:
      - 33cbe3bca207abcb971e5ebbc1dbf2fb
    data: {}
  - delay:
      hours: 0
      minutes: 3
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: 33cbe3bca207abcb971e5ebbc1dbf2fb
    entity_id: 6fcfc0f97f0cc1d0ade2fb6081bb3003
    domain: light
  mode: single
- id: '1730230685787'
  alias: Larissa's Room Lamp Bright Up
  description: ''
  triggers:
  - device_id: c82b911845e876f660de37fa2f9fbc16
    domain: zha
    type: remote_button_short_press
    subtype: turn_on
    trigger: device
  conditions: []
  actions:
  - device_id: 52d37c08bee72c21b8411936cc76f120
    domain: light
    entity_id: 84ab7ba46110ac53dae3386ee6fa4204
    type: brightness_increase
  mode: single
- id: '1730230753678'
  alias: Larissa's Room Lamp Bright Down
  description: ''
  triggers:
  - device_id: c82b911845e876f660de37fa2f9fbc16
    domain: zha
    type: remote_button_short_press
    subtype: turn_off
    trigger: device
  conditions: []
  actions:
  - device_id: 52d37c08bee72c21b8411936cc76f120
    domain: light
    entity_id: 84ab7ba46110ac53dae3386ee6fa4204
    type: brightness_decrease
  mode: single
- id: '1730230831207'
  alias: Larissa's Room Lamp Off
  description: ''
  triggers:
  - device_id: c82b911845e876f660de37fa2f9fbc16
    domain: zha
    type: remote_button_short_press
    subtype: turn_off
    trigger: device
  conditions:
  - condition: numeric_state
    entity_id: light.ikea_of_sweden_tradfri_bulb_e14_ws_candle_470lm_light
    below: 100
    attribute: brightness
    above: -5
  actions:
  - type: turn_off
    device_id: 52d37c08bee72c21b8411936cc76f120
    entity_id: 84ab7ba46110ac53dae3386ee6fa4204
    domain: light
  mode: single
- id: '1730231700700'
  alias: Back Garden Lights On
  description: ''
  triggers:
  - device_id: 181e772e0111dc0e88fe7a8c9c8f12d8
    domain: zha
    type: remote_button_short_press
    subtype: button_1
    trigger: device
  conditions: []
  actions:
  - type: turn_on
    device_id: 882ce8662c7a162d0e4ef714c98f66de
    entity_id: 3f3303fcb4c1965bbc7a73af1b2eaf43
    domain: light
  mode: single
- id: '1730231727273'
  alias: Back Garden Lights Off
  description: ''
  triggers:
  - device_id: 181e772e0111dc0e88fe7a8c9c8f12d8
    domain: zha
    type: remote_button_short_press
    subtype: button_2
    trigger: device
  conditions: []
  actions:
  - type: turn_off
    device_id: 882ce8662c7a162d0e4ef714c98f66de
    entity_id: 3f3303fcb4c1965bbc7a73af1b2eaf43
    domain: light
  mode: single
- id: '1730231901445'
  alias: Back Garden Lights Wall Toggle
  description: ''
  triggers:
  - device_id: 181e772e0111dc0e88fe7a8c9c8f12d8
    domain: zha
    type: remote_button_double_press
    subtype: button_1
    trigger: device
  conditions: []
  actions:
  - type: toggle
    device_id: b5ee12fc16ee670d4460450a09831bfe
    entity_id: 5c16c7859b9e6120b2a53cda3bb7dbe3
    domain: switch
  mode: single
- id: '1730231961903'
  alias: Back Garden Lights Standing Toggle
  description: ''
  triggers:
  - device_id: 181e772e0111dc0e88fe7a8c9c8f12d8
    domain: zha
    type: remote_button_double_press
    subtype: button_2
    trigger: device
  conditions: []
  actions:
  - type: toggle
    device_id: b5ee12fc16ee670d4460450a09831bfe
    entity_id: 1286a7c16ce1e9b136a1704dc3fd64d7
    domain: switch
  mode: single
- id: '1730232125521'
  alias: Front Garden Lights On
  description: ''
  triggers:
  - device_id: dfa89b76741c348af830d9e836a4f929
    domain: zha
    type: remote_button_short_press
    subtype: button_1
    trigger: device
  conditions: []
  actions:
  - type: turn_on
    device_id: 33cbe3bca207abcb971e5ebbc1dbf2fb
    entity_id: 6fcfc0f97f0cc1d0ade2fb6081bb3003
    domain: light
  mode: single
- id: '1730232158467'
  alias: Front Garden Lights Off
  description: ''
  triggers:
  - device_id: dfa89b76741c348af830d9e836a4f929
    domain: zha
    type: remote_button_short_press
    subtype: button_2
    trigger: device
  conditions: []
  actions:
  - type: turn_off
    device_id: 33cbe3bca207abcb971e5ebbc1dbf2fb
    entity_id: 6fcfc0f97f0cc1d0ade2fb6081bb3003
    domain: light
  mode: single
- id: '1730232229737'
  alias: Front Garden Lights Standing Toggle
  description: ''
  triggers:
  - device_id: dfa89b76741c348af830d9e836a4f929
    domain: zha
    type: remote_button_double_press
    subtype: button_2
    trigger: device
  conditions: []
  actions:
  - type: toggle
    device_id: 9d3a3133f20d88096e2a964e62c7e0e7
    entity_id: ea45f65d89c6b8dd0bb25d54dc92e73d
    domain: switch
  mode: single
- id: '1730232267337'
  alias: Front Garden Lights Wall Toggle
  description: ''
  triggers:
  - device_id: dfa89b76741c348af830d9e836a4f929
    domain: zha
    type: remote_button_double_press
    subtype: button_1
    trigger: device
  conditions: []
  actions:
  - type: toggle
    device_id: 9d3a3133f20d88096e2a964e62c7e0e7
    entity_id: 8b2f93fa8b00e17da9186de58f6054cf
    domain: switch
  mode: single
- id: '1730237288919'
  alias: Larissa's Room Fairly Lights Turn Off
  description: ''
  triggers:
  - device_id: c82b911845e876f660de37fa2f9fbc16
    domain: zha
    type: remote_button_long_press
    subtype: dim_down
    trigger: device
  conditions: []
  actions:
  - type: turn_off
    device_id: c1be12d78a8ac8d943f26eab8d7e61d9
    entity_id: 976ac1df78944e87e6e57e7454c910b9
    domain: light
  mode: single
- id: '1730237319753'
  alias: Larissa's Room Fairy Lights Turn On
  description: ''
  triggers:
  - device_id: c82b911845e876f660de37fa2f9fbc16
    domain: zha
    type: remote_button_long_press
    subtype: dim_up
    trigger: device
  conditions: []
  actions:
  - type: turn_on
    device_id: c1be12d78a8ac8d943f26eab8d7e61d9
    entity_id: 976ac1df78944e87e6e57e7454c910b9
    domain: light
  mode: single
- id: '1730471578267'
  alias: Front Garden Switch State Reset Front
  description: ''
  use_blueprint:
    path: silvercory/light_coordinator.yaml
    input:
      switchList:
      - switch.front_light_coordinator_switch_2
      off_duration:
        hours: 0
        minutes: 0
        seconds: 15
- id: '1730471734076'
  alias: Back Garden Switch State Reset Back
  description: ''
  use_blueprint:
    path: silvercory/light_coordinator.yaml
    input:
      switchList:
      - switch.back_light_coordinator_switch
      - switch.back_light_coordinator_switch_2
      off_duration:
        hours: 2
        minutes: 0
        seconds: 0
- id: '1733358901662'
  alias: Living Room Presence Sofa On
  description: ''
  triggers:
  - type: occupied
    device_id: a28dfccb7435331fff4dd2ac950602a1
    entity_id: 158f97d537d7b6dd65aebb943f67c4ac
    domain: binary_sensor
    trigger: device
    for:
      hours: 0
      minutes: 0
      seconds: 2
  conditions: []
  actions:
  - type: turn_on
    device_id: 5e6e95f0b53bbfe13c5cf94ca8d79f86
    entity_id: 6274ac9a0bf914ea9f3271833c478550
    domain: switch
  - type: turn_on
    device_id: e3b6ad06f2bec68670236ae6b968b6bf
    entity_id: 21a004d231482d373b9f4c56576ee52f
    domain: switch
  mode: single
- id: '1733358953976'
  alias: Living Room Presence Sofa Off
  description: ''
  triggers:
  - type: not_occupied
    device_id: a28dfccb7435331fff4dd2ac950602a1
    entity_id: 158f97d537d7b6dd65aebb943f67c4ac
    domain: binary_sensor
    trigger: device
    for:
      hours: 0
      minutes: 15
      seconds: 0
  conditions: []
  actions:
  - type: turn_off
    device_id: 5e6e95f0b53bbfe13c5cf94ca8d79f86
    entity_id: 6274ac9a0bf914ea9f3271833c478550
    domain: switch
  - type: turn_off
    device_id: e3b6ad06f2bec68670236ae6b968b6bf
    entity_id: 21a004d231482d373b9f4c56576ee52f
    domain: switch
  mode: single
- id: '1733359237672'
  alias: Living Room Presence Turn Everything Off
  description: ''
  triggers:
  - type: not_occupied
    device_id: a28dfccb7435331fff4dd2ac950602a1
    entity_id: bbfb94360bd030931b78c8e3b7ca4584
    domain: binary_sensor
    trigger: device
    for:
      hours: 0
      minutes: 20
      seconds: 0
  conditions:
  - condition: time
    after: '21:00:00'
    before: 05:00:00
    weekday:
    - mon
    - tue
    - wed
    - thu
    - sun
    - fri
    - sat
  actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      floor_id: downstairs
  - action: remote.turn_off
    metadata: {}
    data: {}
    target:
      floor_id: downstairs
  mode: single
- id: '1733429670795'
  alias: Living Room Presence Back On
  description: ''
  triggers:
  - type: occupied
    device_id: a28dfccb7435331fff4dd2ac950602a1
    entity_id: 6ed7c1ad34ac626d0dd9c30c97011df9
    domain: binary_sensor
    trigger: device
    for:
      hours: 0
      minutes: 0
      seconds: 5
  conditions:
  - condition: numeric_state
    entity_id: sensor.presence_sensor_fp2_dccc_light_sensor_light_level
    above: -0.3
    below: 25
  actions:
  - type: turn_on
    device_id: 4876fc70f80c68d8120f8991604d678e
    entity_id: 2889e1b77513343c27b8701b1442ca7d
    domain: light
  mode: single
- id: '1733429734891'
  alias: Living Room Presence Back Off
  description: ''
  triggers:
  - type: not_occupied
    device_id: a28dfccb7435331fff4dd2ac950602a1
    entity_id: 6ed7c1ad34ac626d0dd9c30c97011df9
    domain: binary_sensor
    trigger: device
    for:
      hours: 0
      minutes: 0
      seconds: 15
  conditions: []
  actions:
  - type: turn_off
    device_id: 4876fc70f80c68d8120f8991604d678e
    entity_id: 2889e1b77513343c27b8701b1442ca7d
    domain: light
  mode: single
- id: '1733482743270'
  alias: Match Outside Colour Temperature Kelvin
  description: ''
  use_blueprint:
    path: firkeuf/match-color-temp-kelvin.yaml
    input:
      target_lights:
      - light.esphome_corys_light_esphome_corys_room_light
      min_color_temp: 6500
