- id: '1729963391488'
  alias: Cory Returns
  description: ''
  triggers:
  - trigger: zone
    entity_id: person.cory
    zone: zone.home_extended
    event: enter
  - trigger: zone
    entity_id: person.debs
    zone: zone.home_extended
    event: enter
  conditions:
  - condition: sun
    after: sunset
  actions:
  - action: light.turn_on
    target:
      device_id:
      - 33cbe3bca207abcb971e5ebbc1dbf2fb
    data: {}
  - delay:
      hours: 0
      minutes: 3
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: 33cbe3bca207abcb971e5ebbc1dbf2fb
    entity_id: 6fcfc0f97f0cc1d0ade2fb6081bb3003
    domain: light
  mode: single
- id: '1730230685787'
  alias: Larissa's Lamp Bright Up
  description: ''
  triggers:
  - device_id: c82b911845e876f660de37fa2f9fbc16
    domain: zha
    type: remote_button_short_press
    subtype: turn_on
    trigger: device
  conditions: []
  actions:
  - device_id: 52d37c08bee72c21b8411936cc76f120
    domain: light
    entity_id: 84ab7ba46110ac53dae3386ee6fa4204
    type: brightness_increase
  mode: single
- id: '1730230753678'
  alias: Larissa's Lamp Bright Up
  description: ''
  triggers:
  - device_id: c82b911845e876f660de37fa2f9fbc16
    domain: zha
    type: remote_button_short_press
    subtype: turn_off
    trigger: device
  conditions: []
  actions:
  - device_id: 52d37c08bee72c21b8411936cc76f120
    domain: light
    entity_id: 84ab7ba46110ac53dae3386ee6fa4204
    type: brightness_decrease
  mode: single
- id: '1730230831207'
  alias: Larissa's Lamp Off
  description: ''
  triggers:
  - device_id: c82b911845e876f660de37fa2f9fbc16
    domain: zha
    type: remote_button_short_press
    subtype: turn_off
    trigger: device
  conditions:
  - condition: numeric_state
    entity_id: light.ikea_of_sweden_tradfri_bulb_e14_ws_candle_470lm_light
    below: 100
    attribute: brightness
    above: -5
  actions:
  - type: turn_off
    device_id: 52d37c08bee72c21b8411936cc76f120
    entity_id: 84ab7ba46110ac53dae3386ee6fa4204
    domain: light
  mode: single
- id: '1730231700700'
  alias: Back Lights On
  description: ''
  triggers:
  - device_id: 181e772e0111dc0e88fe7a8c9c8f12d8
    domain: zha
    type: remote_button_short_press
    subtype: button_1
    trigger: device
  conditions: []
  actions:
  - type: turn_on
    device_id: 882ce8662c7a162d0e4ef714c98f66de
    entity_id: 3f3303fcb4c1965bbc7a73af1b2eaf43
    domain: light
  mode: single
- id: '1730231727273'
  alias: Back Lights Off
  description: ''
  triggers:
  - device_id: 181e772e0111dc0e88fe7a8c9c8f12d8
    domain: zha
    type: remote_button_short_press
    subtype: button_2
    trigger: device
  conditions: []
  actions:
  - type: turn_off
    device_id: 882ce8662c7a162d0e4ef714c98f66de
    entity_id: 3f3303fcb4c1965bbc7a73af1b2eaf43
    domain: light
  mode: single
- id: '1730231901445'
  alias: Back Lights Wall Toggle
  description: ''
  triggers:
  - device_id: 181e772e0111dc0e88fe7a8c9c8f12d8
    domain: zha
    type: remote_button_double_press
    subtype: button_1
    trigger: device
  conditions: []
  actions:
  - type: toggle
    device_id: b5ee12fc16ee670d4460450a09831bfe
    entity_id: 5c16c7859b9e6120b2a53cda3bb7dbe3
    domain: switch
  mode: single
- id: '1730231961903'
  alias: Back Lights Standing Toggle
  description: ''
  triggers:
  - device_id: 181e772e0111dc0e88fe7a8c9c8f12d8
    domain: zha
    type: remote_button_double_press
    subtype: button_2
    trigger: device
  conditions: []
  actions:
  - type: toggle
    device_id: b5ee12fc16ee670d4460450a09831bfe
    entity_id: 1286a7c16ce1e9b136a1704dc3fd64d7
    domain: switch
  mode: single
- id: '1730232125521'
  alias: Front Lights On
  description: ''
  triggers:
  - device_id: dfa89b76741c348af830d9e836a4f929
    domain: zha
    type: remote_button_short_press
    subtype: button_1
    trigger: device
  conditions: []
  actions:
  - type: turn_on
    device_id: 33cbe3bca207abcb971e5ebbc1dbf2fb
    entity_id: 6fcfc0f97f0cc1d0ade2fb6081bb3003
    domain: light
  mode: single
- id: '1730232158467'
  alias: Front Lights Off
  description: ''
  triggers:
  - device_id: dfa89b76741c348af830d9e836a4f929
    domain: zha
    type: remote_button_short_press
    subtype: button_2
    trigger: device
  conditions: []
  actions:
  - type: turn_off
    device_id: 33cbe3bca207abcb971e5ebbc1dbf2fb
    entity_id: 6fcfc0f97f0cc1d0ade2fb6081bb3003
    domain: light
  mode: single
- id: '1730232229737'
  alias: Front Lights Standing Toggle
  description: ''
  triggers:
  - device_id: dfa89b76741c348af830d9e836a4f929
    domain: zha
    type: remote_button_double_press
    subtype: button_2
    trigger: device
  conditions: []
  actions:
  - type: toggle
    device_id: 9d3a3133f20d88096e2a964e62c7e0e7
    entity_id: ea45f65d89c6b8dd0bb25d54dc92e73d
    domain: switch
  mode: single
- id: '1730232267337'
  alias: Front Lights Wall Toggle
  description: ''
  triggers:
  - device_id: dfa89b76741c348af830d9e836a4f929
    domain: zha
    type: remote_button_double_press
    subtype: button_1
    trigger: device
  conditions: []
  actions:
  - type: toggle
    device_id: 9d3a3133f20d88096e2a964e62c7e0e7
    entity_id: 8b2f93fa8b00e17da9186de58f6054cf
    domain: switch
  mode: single
- id: '1730237288919'
  alias: Fairly Lights Turn Off
  description: ''
  triggers:
  - device_id: c82b911845e876f660de37fa2f9fbc16
    domain: zha
    type: remote_button_long_press
    subtype: dim_down
    trigger: device
  conditions: []
  actions:
  - type: turn_off
    device_id: c1be12d78a8ac8d943f26eab8d7e61d9
    entity_id: 70da9f9c09aa0e6e8d6a0b356c88a075
    domain: light
  mode: single
- id: '1730237319753'
  alias: Fairy Lights Turn On
  description: ''
  triggers:
  - device_id: c82b911845e876f660de37fa2f9fbc16
    domain: zha
    type: remote_button_long_press
    subtype: dim_up
    trigger: device
  conditions: []
  actions:
  - type: turn_on
    device_id: c1be12d78a8ac8d943f26eab8d7e61d9
    entity_id: 70da9f9c09aa0e6e8d6a0b356c88a075
    domain: light
  mode: single
- id: '1730471578267'
  alias: Switch State Reset Front
  description: ''
  use_blueprint:
    path: silvercory/light_coordinator.yaml
    input:
      switchList:
      - switch.front_light_coordinator_switch
      - switch.front_light_coordinator_switch_2
      off_duration:
        hours: 0
        minutes: 0
        seconds: 15
- id: '1730471734076'
  alias: Switch State Reset Back
  description: ''
  use_blueprint:
    path: silvercory/light_coordinator.yaml
    input:
      switchList:
      - switch.back_light_coordinator_switch
      off_duration:
        hours: 2
        minutes: 0
        seconds: 0
