# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies: 192.168.1.180

stream:

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

google_assistant:
  project_id: home-assistant-h-1605267715757
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true
  exposed_domains:
    - switch
    - light
    - scene
    - camera
    - alarm_control_panel
    - button
    - climate
    - cover
    - event
    - fan
    - group
    - humidifier
    - input_boolean
    - input_button
    - input_select
    - lawn_mower
    - lock
    - media_player
    - script
    - select
    - sensor
    - vacuum
    - valve
    - water_heater
  entity_config:
    climate.house_thermostat:
      expose: false

zha:
  zigpy_config:
    ota:
      extra_providers:
        - type: "ikea"
        - type: "ledvance"
        - type: "salus"
        - type: "inovelli"
        - type: "thirdreality"

zha_toolkit:

shell_command: 
    fm: which ffmpeg
    av: which avconv
