blueprint:
  name: Match Outside Colour Temperature Kelvin
  description: When a light turns on or the sun elevation changes match the outside
    colour temperature. It will apply to any bulb that supports color temperature.
    It triggers whenever a bulb turns on, on sun elevation changes and every 5 minutes.
  domain: automation
  input:
    target_lights:
      name: Lights
      description: The primary lights to be controlled
      selector:
        entity:
          domain:
          - light
          multiple: true
    min_color_temp:
      name: Coolest Color Temperature
      description: The coolest color your bulbs will be set to
      default: 4000
      selector:
        number:
          min: 1500.0
          max: 6500.0
          step: 1.0
          mode: slider
    max_color_temp:
      name: Warmest Color Temperature
      description: The warmest color your bulbs will be set to
      default: 2202
      selector:
        number:
          min: 1500.0
          max: 6500.0
          step: 1.0
          mode: slider
    brightness_action:
      name: Brightness
      description: When a device turns on its color temperature will be set, this
        may interfere with the brightness, this action will run half a second later
        to set the light's brightness.
      selector:
        action: {}
      default:
      - service: light.turn_on
        data:
          brightness: '{{max(trigger.to_state.attributes.brightness,2)}}'
        target:
          entity_id: '{{trigger.entity_id}}'
        alias: Default - Set light to its original brightness, don't use brightness
          1 as it causes issues with some bulbs
  source_url: https://gist.github.com/firkeuf/8ef27755b1bb2dcd5bbe89c7e1f56d9b
variables:
  target_lights: !input target_lights
  min_color_temp: !input min_color_temp
  max_color_temp: !input max_color_temp
  color_temp: '{{ [([(((4791.67 - 3290.66/(1 + 0.222 * ([([0,state_attr(''sun.sun'',
    ''elevation'')]|max),90]|min**0.81))))|int),max_color_temp]|max),min_color_temp]|min}}'
  target_on_lights: '{{states.light | selectattr(''state'',''eq'',''on'') | selectattr(''attributes.supported_color_modes'',''match'',".*color_temp.*")
    | selectattr("attributes.color_temp_kelvin","eq", color_temp) | map(attribute=''entity_id'')
    | select("in",target_lights) | list }}'
trigger:
- platform: state
  entity_id: !input target_lights
  to: 'on'
  id: single_light_on
- platform: state
  entity_id:
  - sun.sun
  attribute: elevation
  id: elevation_change
- platform: time_pattern
  minutes: '5'
  id: every_5_min
condition:
- condition: template
  value_template: '{{ (states.light | selectattr(''state'',''eq'',''on'') | map(attribute=''entity_id'')
    | list)!= [] }}'
action:
- choose:
  - conditions:
    - condition: trigger
      id: single_light_on
    sequence:
    - if:
      - condition: or
        conditions:
        - condition: template
          value_template: '{{ states(''input_number.%s_temp'' | format(trigger.entity_id
            | replace(''.'', ''_''))) | int == trigger.to_state.attributes.color_temp
            }}'
        - condition: template
          value_template: '{{ states(''input_number.%s_temp'' | format(trigger.entity_id
            | replace(''.'', ''_''))) | int == 1000 }}'
      then:
      - service: input_number.set_value
        target:
          entity_id: '{{ ''input_number.%s_temp'' | format(trigger.entity_id | replace(''.'',
            ''_'')) }}'
        data:
          value: '{{ (1000000/color_temp) | int }}'
      - service: light.turn_on
        data:
          kelvin: '{{color_temp}}'
        target:
          entity_id: '{{trigger.entity_id}}'
      - delay:
          milliseconds: 500
      - choose:
        default: !input brightness_action
  - conditions:
    - condition: or
      conditions:
      - condition: trigger
        id: every_5_min
      - condition: trigger
        id: elevation_change
    sequence:
    - repeat:
        sequence:
        - if:
          - condition: or
            conditions:
            - condition: template
              value_template: '{{ state_attr(repeat.item, ''color_temp'') ==  states(''input_number.%s_temp''
                | format(repeat.item | replace(''.'', ''_''))) | int}}'
            - condition: template
              value_template: '{{ states(''input_number.%s_temp'' | format(repeat.item
                | replace(''.'', ''_''))) | int == 1000 }}'
          then:
          - service: python_script.hass_entities
            data:
              action: set_attributes
              entity_id: '{{repeat.item}}'
              attributes:
              - custom_color_temp_prev: '{{ 1000000//color_temp }}'
        for_each: '{{states.light | selectattr(''state'',''eq'',''on'') | selectattr(''attributes.supported_color_modes'',''match'',".*color_temp.*")
          |  map(attribute=''entity_id'') | select("in",target_lights) | list }}'
    - variables:
        target_on_lights: '{{states.light | selectattr(''state'',''eq'',''on'') |
          selectattr(''attributes.supported_color_modes'',''match'',".*color_temp.*")
          |  selectattr("attributes.custom_color_temp_prev","gt", 1000000//color_temp
          - 2) | selectattr("attributes.custom_color_temp_prev","lt", 1000000//color_temp
          + 2) | map(attribute=''entity_id'') | select("in",target_lights)  | list
          }}'
    - service: light.turn_on
      data:
        kelvin: '{{color_temp}}'
        transition: 5
      target:
        entity_id: '{{target_on_lights}}'
    - repeat:
        sequence:
        - service: input_number.set_value
          target:
            entity_id: '{{ ''input_number.%s_temp'' | format(repeat.item | replace(''.'',
              ''_'')) }}'
          data:
            value: '{{ (1000000/color_temp) | int }}'
        for_each: '{{states.light | map(attribute=''entity_id'') | select("in",target_on_lights)
          | list }}'
mode: parallel
