esphome:
  name: garage-door
  friendly_name: garage-door

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "1ztq6x+rvyc1yLtVNsXy/luhK3HTdsT6jXIKaikk8is="

ota:
  - platform: esphome
    password: "bd0608cc74ec824884ecfcfa7e25d24d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage-Door Fallback Hotspot"
    password: "YTjtjMeN0wTK"

captive_portal:
    