blueprint:
  name: Light Coordinator State Reset Template
  description: Re-enable light coordinator switches after a period.
  domain: automation
  input:
    coord_switch_a:
      name: Coordinator Switch A
      description: The first coordinator switch to reset after a period.
      selector:
        entity:
          domain: switch
    coord_switch_b:
      name: Coordinator Switch B
      description: The second coordinator switch to reset after a period.
      selector:
        entity:
          domain: switch
    off_duration:
      name: Off Duration
      description: Duration in HH:MM:SS for which the entities should remain off before turning back on.
      selector:
        duration: {}

trigger:
  - platform: state
    entity_id: !input coord_switch_a
    to: "off"
    for: !input off_duration
  - platform: state
    entity_id: !input coord_switch_b
    to: "off"
    for: !input off_duration

condition: []

action:
  - service: switch.turn_on
    target:
      entity_id:
        - !input coord_switch_a
        - !input coord_switch_b

mode: restart
