blueprint:
  name: Switch State Reset Template
  description: Re-enable light coordinator switches after a period.
  domain: automation
  input:
    switchList:
      name: Switches
      description: The first coordinator switch to reset after a period.
      selector:
        entity:
          domain: switch
          multiple: true
    off_duration:
      name: Off Duration
      description: Duration in HH:MM:SS for which the entities should remain off before turning back on.
      selector:
        duration: {}

trigger:
  - platform: state
    entity_id: !input !input switchList
    to: "off"
    for: !input off_duration

condition: []

action:
  - service: switch.turn_on
    target:
      entity_id: !input switchList

mode: restart
