blueprint:
  name: Back Light Coordinator State Reset Template
  description: Turn off two entities for a specified duration and turn them back on after.
  domain: automation
  input:
    target_device:
      name: Target Device
      description: The device to monitor for the state change.
      selector:
        device:
    entity_one:
      name: First Entity to Monitor
      description: The first entity to turn off for the duration.
      selector:
        entity:
          domain: switch
    entity_two:
      name: Second Entity to Monitor
      description: The second entity to turn off for the duration.
      selector:
        entity:
          domain: switch
    off_duration:
      name: Off Duration
      description: Duration in HH:MM:SS for which the entities should remain off before turning back on.
      selector:
        duration: {}

trigger:
  - platform: state
    entity_id: !input entity_one
    to: "off"
    for: !input off_duration
  - platform: state
    entity_id: !input entity_two
    to: "off"
    for: !input off_duration

condition: []

action:
  - service: switch.turn_on
    target:
      entity_id:
        - !input entity_one
        - !input entity_two

mode: single
