blueprint:
  name: Back Light Coordinator State Reset Template
  description: Turn off two entities for a specified duration and turn them back on after.
  domain: automation
  input:
    target_device:
      name: Target Device
      description: The device to monitor for the state change.
      selector:
        device:
    entity_one:
      name: First Entity to Monitor
      description: The first entity to turn off for the duration.
      selector:
        entity:
          domain: switch
    entity_two:
      name: Second Entity to Monitor
      description: The second entity to turn off for the duration.
      selector:
        entity:
          domain: switch
    off_duration:
      name: Duration (hours)
      description: Duration in hours for the entities to be off before turning back on.
      selector:
        number:
          min: 0
          max: 24
          unit_of_measurement: hours
          mode: slider
          step: 1

trigger:
  - platform: state
    entity_id: !input entity_one
    to: "off"
    for:
      hours: !input off_duration
      minutes: 0
      seconds: 0
  - platform: state
    entity_id: !input entity_two
    to: "off"
    for:
      hours: !input off_duration
      minutes: 0
      seconds: 0

condition: []

action:
  - service: switch.turn_on
    target:
      entity_id:
        - !input entity_one
        - !input entity_two

mode: restart
