esphome:
  name: esp-rf433-hub
  friendly_name: esp-rf433-hub

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "oFIaGUx/WOgoQg9qT7P9Eel6Mg2NhCbm/g03tepPPiU="

ota:
  - platform: esphome
    password: "0cd40678b1f9112159e182e19b23c7b1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Rf433-Hub Fallback Hotspot"
    password: "jfykVNNuoyxv"

web_server:
 port: 80

captive_portal:

remote_receiver:
  pin: GPIO4
  dump: all

remote_transmitter:
  pin: GPIO0
  carrier_duty_percent: 100%

switch:
  - platform: template
    name: "Doorbell Ring Lock"
    id: doorbell_lock
    internal: true
    optimistic: true
    on_turn_on: 
      then:
        - logger.log: "Doorbell Chime Triggered. Lock active for 10s."
        - delay: 
            10s
        - switch.turn_off: doorbell_lock
button:
  - platform: template
    name: Doorbell Chime Ring
    icon: mdi:bell-ring
    id: doorbell_chime_button
    on_press:
      - if:
          condition:
            switch.is_off: doorbell_lock
          then:
            - switch.turn_on: doorbell_lock
            - remote_transmitter.transmit_rc_switch_raw:
                code: '101111000110001101000011'
                protocol: 
                  pulse_length: 185
                repeat:
                  times: 10
                  wait_time: 0s