substitutions:
  name: esphome-corys-light
  friendly_name: ESPHome Corys Room Light

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point
  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp8266.yaml@main
  import_full_config: true

# To have a "next url" for improv serial
web_server:

output:
  - platform: esp8266_pwm
    id: output_r
    pin: GPIO4
  - platform: esp8266_pwm
    id: output_cw
    pin: GPIO5
  - platform: esp8266_pwm
    pin: GPIO12
    id: output_g
  - platform: esp8266_pwm
    pin: GPIO13
    id: output_ww
  - platform: esp8266_pwm
    pin: GPIO14
    id: output_b

# This component provides sun information
sun:
  latitude: 0.1
  longitude: 0.1

# Scripts for calculating color temperature and brightness with linear interpolation
script:
  - id: 'hello'
    then: []

  - id: sun_color_temp
    then:
      - lambda: |-
          auto elevation = id(sun).elevation;
          float color_temp_low = 2700;  // For low elevation
          float color_temp_high = 6500; // For high elevation
          float elevation_low = 0;      // Elevation for color_temp_low
          float elevation_high = 45;    // Elevation for color_temp_high
          float color_temp = color_temp_low + (elevation - elevation_low) * (color_temp_high - color_temp_low) / (elevation_high - elevation_low);
          return color_temp;

  - id: sun_brightness
    then:
      - lambda: |-
          auto elevation = id(sun).elevation;
          float brightness_low = 0.2;   // For low elevation
          float brightness_high = 1.0;  // For high elevation
          float elevation_low = 0;      // Elevation for brightness_low
          float elevation_high = 45;    // Elevation for brightness_high
          float brightness = brightness_low + (elevation - elevation_low) * (brightness_high - brightness_low) / (elevation_high - elevation_low);
          return brightness;

light:
  - platform: rgbww
    color_interlock: true
    name: ${friendly_name}
    red: output_r
    green: output_g
    blue: output_b
    warm_white: output_ww
    cold_white: output_cw
    cold_white_color_temperature: 5700 K
    warm_white_color_temperature: 3000 K
    color_temperature: !lambda sun_color_temp
    brightness: !lambda sun_brightness
    gamma_correct: true       # For smoother brightness transitions
    transition_length: 5s      # Add a transition time (adjust as needed)