esphome:
  name: garage-door
  friendly_name: garage-door

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "ZQynlNs4M9MNhK2PsNmmxdhazJnhKXZ8Zq+q4B8UzMs="

ota:
  - platform: esphome
    password: "5cf411f880e8bf616a8b7601b65f92ac"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage-Door Fallback Hotspot"
    password: "TZ86GYtFOuIx"

captive_portal:

external_components:
  - source: 'github://SilverCory/esphome-components@5c2722ffe5d3a78a46efb5a2c8803b71c0d7d040'

uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 19200
  stop_bits: 1

hoermann_controller:
  id: hoermann_door_controller
  uart_id: uart_bus
  de_pin: GPIO4

cover:
  - platform: hoermann_controller
    hoermann_controller_id: hoermann_door_controller
    name: "${friendly_name}"

switch:
  - platform: hoermann_controller
    hoermann_controller_id: hoermann_door_controller
    type: 'light'
    name: "${friendly_name} Light"
    icon: "mdi:lightbulb"

  - platform: hoermann_controller
    hoermann_controller_id: hoermann_door_controller
    type: 'venting'
    name: "${friendly_name} Venting"
    icon: "mdi:fan"

binary_sensor:
  - platform: hoermann_controller
    hoermann_controller_id: hoermann_door_controller
    type: 'error'
    name: "${friendly_name} Error"
    device_class: problem

  - platform: hoermann_controller
    hoermann_controller_id: hoermann_door_controller
    type: 'prewarn'
    name: "${friendly_name} Pre-Warning"
    device_class: safety

  - platform: hoermann_controller
    hoermann_controller_id: hoermann_door_controller
    type: 'option_relay'
    name: "${friendly_name} Option Relay"
    device_class: power

button:
  - platform: hoermann_controller
    hoermann_controller_id: hoermann_door_controller
    type: 'impulse'
    name: "${friendly_name} Impulse"
    icon: "mdi:arrow-up-down"

  - platform: hoermann_controller
    hoermann_controller_id: hoermann_door_controller
    type: 'emergency_stop'
    name: "${friendly_name} Emergency Stop"
    icon: "mdi:alert-octagon"

